// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUwRT-EaJsQwHbD9Q65hxi3XqVv_kv8K8',
    appId: '1:373666903600:web:4206c415e73b9ee8a11ff5',
    messagingSenderId: '373666903600',
    projectId: 'kaddug-yalla-gi-plus',
    authDomain: 'kaddug-yalla-gi-plus.firebaseapp.com',
    storageBucket: 'kaddug-yalla-gi-plus.appspot.com',
    measurementId: 'G-9GD9CR8NLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZwKU-BiHVQJUYs2YOqa08BE5HnfJQzjU',
    appId: '1:373666903600:android:f2b59e7397be89cba11ff5',
    messagingSenderId: '373666903600',
    projectId: 'kaddug-yalla-gi-plus',
    storageBucket: 'kaddug-yalla-gi-plus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATDnt1UL_ByWCPtQ9BxqH-SvDAlv9Cww8',
    appId: '1:373666903600:ios:588f8786f286b558a11ff5',
    messagingSenderId: '373666903600',
    projectId: 'kaddug-yalla-gi-plus',
    storageBucket: 'kaddug-yalla-gi-plus.appspot.com',
    iosClientId: '373666903600-km17icdd2nhufu9a58u2tvd32qblhj4d.apps.googleusercontent.com',
    iosBundleId: 'org.mbs.kygplus.wol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATDnt1UL_ByWCPtQ9BxqH-SvDAlv9Cww8',
    appId: '1:373666903600:ios:588f8786f286b558a11ff5',
    messagingSenderId: '373666903600',
    projectId: 'kaddug-yalla-gi-plus',
    storageBucket: 'kaddug-yalla-gi-plus.appspot.com',
    iosClientId: '373666903600-km17icdd2nhufu9a58u2tvd32qblhj4d.apps.googleusercontent.com',
    iosBundleId: 'org.mbs.kygplus.wol',
  );
}
